name: Deploy
on:
    push: 

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Create config
              run: mkdir ~/.kube; echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
              
            - name: Open IPFS Tunnel
              run: kubectl -n ipfs port-forward ipfs-ipfs-0 5001:5001 &

            - name: Download IPFS
              run: wget https://github.com/ipfs/go-ipfs/releases/download/v0.6.0/go-ipfs_v0.6.0_linux-amd64.tar.gz

            - name: Unpack IPFS
              run: tar -xvzf go-ipfs_v0.6.0_linux-amd64.tar.gz
          
            - name: Install dependencies
              run: npm install
          
            - name: Build
              run: npm run build
            
            - name: Publish to IPFS
              run: | 
                export HASH=$(./go-ipfs/ipfs add -r build/ --api=/ip4/127.0.0.1/tcp/5001 -Q)
                echo ::set-output name=HASH::$HASH
              id: get_hash
    
            - name: Update DNSLink
              env:
                CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
                RECORD_DOMAIN: 'shyim.me'
                RECORD_NAME: '_dnslink'
                CLOUDFLARE_TOKEN_ZONE_ID: ${{ secrets.CLOUDFLARE_TOKEN_ZONE_ID }}
              id: dnslink
              uses: textileio/cloudflare-update-dnslink@master
              with:
                cid: ${{ steps.get_hash.outputs.HASH }}
               
